// flow-typed signature: 7a10b7c694dfbe5f8a8372734b4e9091
// flow-typed version: <<STUB>>/jest-jasmine2_v^19.0.2/flow_v0.40.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'jest-jasmine2'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'jest-jasmine2' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'jest-jasmine2/build/index' {
  declare module.exports: any;
}

declare module 'jest-jasmine2/build/jasmine-async' {
  declare module.exports: any;
}

declare module 'jest-jasmine2/build/jest-expect' {
  declare module.exports: any;
}

declare module 'jest-jasmine2/build/reporter' {
  declare module.exports: any;
}

declare module 'jest-jasmine2/build/setup-jest-globals' {
  declare module.exports: any;
}

declare module 'jest-jasmine2/vendor/jasmine-2.5.2' {
  declare module.exports: any;
}

// Filename aliases
declare module 'jest-jasmine2/build/index.js' {
  declare module.exports: $Exports<'jest-jasmine2/build/index'>;
}
declare module 'jest-jasmine2/build/jasmine-async.js' {
  declare module.exports: $Exports<'jest-jasmine2/build/jasmine-async'>;
}
declare module 'jest-jasmine2/build/jest-expect.js' {
  declare module.exports: $Exports<'jest-jasmine2/build/jest-expect'>;
}
declare module 'jest-jasmine2/build/reporter.js' {
  declare module.exports: $Exports<'jest-jasmine2/build/reporter'>;
}
declare module 'jest-jasmine2/build/setup-jest-globals.js' {
  declare module.exports: $Exports<'jest-jasmine2/build/setup-jest-globals'>;
}
declare module 'jest-jasmine2/vendor/jasmine-2.5.2.js' {
  declare module.exports: $Exports<'jest-jasmine2/vendor/jasmine-2.5.2'>;
}
